
services:
  website:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - front-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    env_file: 
      - .env
    depends_on:
      - website 
    command: >
      http website:80
    networks:
      - front-net
    ports:
      - "4040:4040"

networks:
  front-net:
    external: true  #không tạo mới